### ISSUE TITLE
Composer download from TYPO3 extension repository fails

### ISSUE THREAD

**Issue by wabajwa** [dwenzel/t3calendar#5]
Hi,
I am trying to install the `t3calendar`via composer but it is giving me the following error. 
![image](https://cloud.githubusercontent.com/assets/24478656/24284682/c9aaed24-106c-11e7-993c-507554861aa7.png)

Looking forward for some help.
Thanks

**Comment by dwenzel** [comment]
Hi and thank you for reporting this issue.
It seems that the TYPO3 extension repository does not work correctly. 
I recently noticed that the extension repository browser doesn't display _t3calendar_ under `https://typo3.org/extensions/repository/view/t3calendar` (as expected) but under `...t3calendar-1`.

I will open an issue at typo3.org.
Meanwhile please try `require dwenzel/t3calendar`. This is the composer key registered with packagist.org

cheers
Dirk

**Comment by dwenzel** [comment]
Issue on TYPO3 forge: https://forge.typo3.org/issues/80435

**Comment by dwenzel** [comment]
@wabajwa The issue has been resolved by the TYPO3 TER team. Composer install now works with `require typo3-ter/t3calendar` again.

**Comment by wabajwa** [comment]
Its working now, thank you so much.
